In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    "../data/events_features.csv"
)

df.head()

,id,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,...,year,duration_hours,cause_score,closure_score,priority_score,impact_score,risk_level,weekend,lat_grid,lon_grid
0,FKID000000,unplanned,13.040004,77.518099,0.000000,0.000000,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,...,2024.0,NaN,2.0,0,5.0,7.0,Medium,0,13.04,77.52
1,FKID000001,unplanned,12.921876,77.645158,0.000000,0.000000,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",NaN,vehicle_breakdown,False,...,2024.0,NaN,2.0,0,5.0,7.0,Medium,0,12.92,77.65
2,FKID000002,unplanned,12.955622,77.585708,0.000000,0.000000,"Lalbagh Main Road, Dr Sri Shantaveera Swami Ci...",NaN,others,False,...,2023.0,NaN,3.0,0,1.0,4.0,Low,1,12.96,77.59
3,FKID000003,unplanned,13.006147,77.579435,13.006239,77.579516,"Sankey Road, Bashyam Circle, Sadashiva Nagar, ...","Sankey Road, Palace Orchard Upper, Sadashiva N...",tree_fall,True,...,2024.0,NaN,5.0,5,1.0,11.0,High,0,13.01,77.58
4,FKID000004,unplanned,12.953980,77.585233,0.000000,0.000000,"Lalbagh Fort Road, Lalbagh Main Gate Junction,...",NaN,vehicle_breakdown,False,...,2024.0,NaN,2.0,0,1.0,3.0,Low,0,12.95,77.59

In [3]:
pd.crosstab(
    df["event_cause"],
    df["risk_level"]
)

risk_level            Critical  High   Low  Medium
event_cause
Debris                       0     0     3       9
Fog / Low Visibility         0     0     1       1
accident                     5   169     0     191
congestion                   2    96     0      38
construction                68   293     0     119
debris                       0     1     0       0
others                       0    30   233     375
pot_holes                    0     5   230     302
procession                  19    53     0       0
protest                      6     9     0       0
public_event                15    51     0      18
road_conditions              0    21     0     149
test_demo                    0     0     2       1
tree_fall                    0   112     0     172
vehicle_breakdown            2   100  1543    3251
vip_movement                16     4     0       0
water_logging                0    22   170     266

In [4]:
resource_map = {
    "Critical": 20,
    "High": 10,
    "Medium": 5,
    "Low": 2
}

df["officer_score"] = (
    df["risk_level"]
    .map(resource_map)
)

In [5]:
resource_table = (
    df.groupby(
        "event_cause"
    )["officer_score"]
    .mean()
    .round()
    .reset_index()
)

resource_table

             event_cause  officer_score
0                 Debris            4.0
1   Fog / Low Visibility            4.0
2               accident            8.0
3             congestion            9.0
4           construction           10.0
5                 debris           10.0
6                 others            4.0
7              pot_holes            4.0
8             procession           13.0
9                protest           14.0
10          public_event           11.0
11       road_conditions            6.0
12             test_demo            3.0
13             tree_fall            7.0
14     vehicle_breakdown            4.0
15          vip_movement           18.0
16         water_logging            4.0

In [6]:
resource_table["officers"] = (
    resource_table["officer_score"]
)

resource_table["barricades"] = (
    resource_table["officers"] // 2
)

resource_table["diversions"] = (
    resource_table["officers"] // 5
)

resource_table

             event_cause  officer_score  officers  barricades  diversions
0                 Debris            4.0       4.0         2.0         0.0
1   Fog / Low Visibility            4.0       4.0         2.0         0.0
2               accident            8.0       8.0         4.0         1.0
3             congestion            9.0       9.0         4.0         1.0
4           construction           10.0      10.0         5.0         2.0
5                 debris           10.0      10.0         5.0         2.0
6                 others            4.0       4.0         2.0         0.0
7              pot_holes            4.0       4.0         2.0         0.0
8             procession           13.0      13.0         6.0         2.0
9                protest           14.0      14.0         7.0         2.0
10          public_event           11.0      11.0         5.0         2.0
11       road_conditions            6.0       6.0         3.0         1.0
12             test_demo            3.0       3.0         1.0         0.0
13             tree_fall            7.0       7.0         3.0         1.0
14     vehicle_breakdown            4.0       4.0         2.0         0.0
15          vip_movement           18.0      18.0         9.0         3.0
16         water_logging            4.0       4.0         2.0         0.0

In [7]:
resource_table.sort_values(
    "officers",
    ascending=False
)

             event_cause  officer_score  officers  barricades  diversions
15          vip_movement           18.0      18.0         9.0         3.0
9                protest           14.0      14.0         7.0         2.0
8             procession           13.0      13.0         6.0         2.0
10          public_event           11.0      11.0         5.0         2.0
4           construction           10.0      10.0         5.0         2.0
5                 debris           10.0      10.0         5.0         2.0
3             congestion            9.0       9.0         4.0         1.0
2               accident            8.0       8.0         4.0         1.0
13             tree_fall            7.0       7.0         3.0         1.0
11       road_conditions            6.0       6.0         3.0         1.0
14     vehicle_breakdown            4.0       4.0         2.0         0.0
0                 Debris            4.0       4.0         2.0         0.0
1   Fog / Low Visibility            4.0       4.0         2.0         0.0
7              pot_holes            4.0       4.0         2.0         0.0
6                 others            4.0       4.0         2.0         0.0
16         water_logging            4.0       4.0         2.0         0.0
12             test_demo            3.0       3.0         1.0         0.0

In [8]:
resource_table.to_csv(
    "../data/resource_plan.csv",
    index=False
)